### ISSUE TITLE
Cannot execute `git clone`

### ISSUE THREAD

**Issue by everywan** [NeoTerrm/NeoTerm#9]
After install git, cannot execute `git clone`. 
执行`git clone`时, 程序开始复制然后直接退出,没有实际操作.
手机没有root, 机型是小米 MIX2, miui8/9 都不行.

**Comment by licaon-kter** [comment]
Error messages?

**Comment by everywan** [comment]
![screenshot_2017-10-12-17-28-51-855_io neoterm](https://user-images.githubusercontent.com/10541951/31489362-f747efca-af72-11e7-8bcd-c42b3378c083.png)
No Error msg..

**Comment by everywan** [comment]
![img_20171012_173409](https://user-images.githubusercontent.com/10541951/31489586-b64f7d84-af73-11e7-8c31-c146a67321d1.png)
No Error msg..

**Comment by licaon-kter** [comment]
Working fine here (albeit I needed to [apt install libssh2](https://github.com/NeoTerm/NeoTerm/issues/4)), with a new empty repo.

**Comment by ghost** [comment]
请确认你的软件包是否完全安装，或者输入apt-get install --fix-missing检查是否安装完整c4droid-------- 原始邮件 --------主题：Re: [NeoTerm/NeoTerm] Cannot execute `git clone` (#9)发件人：everywan 收件人：NeoTerm/NeoTerm 抄送：Subscribed 
No Error msg..

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/NeoTerm/NeoTerm","title":"NeoTerm/NeoTerm","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/NeoTerm/NeoTerm"}},"updates":{"snippets":[{"icon":"PERSON","message":"@everywan in #9: ![img_20171012_173409](https://user-images.githubusercontent.com/10541951/31489586-b64f7d84-af73-11e7-8c31-c146a67321d1.png)\r\nNo Error msg.."}],"action":{"name":"View Issue","url":"https://github.com/NeoTerm/NeoTerm/issues/9#issuecomment-336075575"}}}

**Comment by everywan** [comment]
After install libssh2, git works.
thanks!
